owner: LeastAuthority
repo: end-users-upptime

sites:
  - name: Least Authority - website
    url: https://www.leastauthority.com/
  - name: Private Storage - website
    url: https://private.storage/
  - name: Winden - website
    url: https://winden.app/
  - name: Magic Wormhole - mailbox
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/wormhole-icon.png
    url: https://mailbox.mw.leastauthority.com/
  - name: Magic Wormhole - relay
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/wormhole-icon.png
    url: https://relay.mw.leastauthority.com/
  - name: HRO Cloud - storage001
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage001.deerfield.leastauthority.com
    port: 8898
  - name: HRO Cloud - storage002
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage002.deerfield.leastauthority.com
    port: 8898
  - name: HRO Cloud - storage003
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage003.deerfield.leastauthority.com
    port: 8898

status-website:
  baseUrl: /end-users-upptime
  logoUrl: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This site monitor public resources of LA
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
