owner: LeastAuthority
repo: end-users-upptime

sites:
  - name: Least Authority - website
    url: https://www.leastauthority.com/
  - name: Least Authority - redirect
    url: http://leastauthority.com/
    expectedStatusCodes:
      - 301
  - name: Least Authority - de redirect
    url: http://leastauthority.de/
    expectedStatusCodes:
      - 302
  - name: Winden - website
    url: https://winden.app/
  - name: Winden - redirect
    url: http://winden.app/
    expectedStatusCodes:
      - 301
  - name: Winden - it redirect
    url: http://winden.it/
    expectedStatusCodes:
      - 301
  - name: Winden - me redirect
    url: http://winden.me/
    expectedStatusCodes:
      - 301
  - name: Winden - tech redirect
    url: http://winden.tech/
    expectedStatusCodes:
      - 301
  - name: Magic Wormhole - mailbox
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/wormhole-icon.png
    url: https://mailbox.mw.leastauthority.com/
  - name: Magic Wormhole - relay
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/wormhole-icon.png
    url: https://relay.mw.leastauthority.com/
  - name: CDR Link - helpdesk support
    url: https://leastauthority.cdr.link/
  - name: HRO Cloud - payment API
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: payments.deerfield.leastauthority.com
    port: 443
  - name: HRO Cloud - storage001
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage001.deerfield.leastauthority.com
    port: 8898
  - name: HRO Cloud - storage002
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage002.deerfield.leastauthority.com
    port: 8898
  - name: HRO Cloud - storage003
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/tahoelafs-icon.png
    check: "tcp-ping"
    url: storage003.deerfield.leastauthority.com
    port: 8898
  - name: Private Storage - website
    url: https://private.storage/
  - name: Private Storage - redirect
    url: http://private.storage/
    expectedStatusCodes:
      - 301
  - name: Private Storage - app redirect
    url: http://privatestorage.app/
    expectedStatusCodes:
      - 303
  - name: Private Storage - dev redirect
    url: http://privatestorage.dev/
    expectedStatusCodes:
      - 303
  - name: Private Storage - io redirect
    url: http://privatestorage.io/
    expectedStatusCodes:
      - 301
  - name: Private Storage - online redirect
    url: http://privatestorage.online/
    expectedStatusCodes:
      - 302
  - name: Private Storage - org redirect
    url: http://privatestorage.org/
    expectedStatusCodes:
      - 303
  - name: Private Storage - tech redirect
    url: http://privatestorage.tech/
    expectedStatusCodes:
      - 303
  - name: Private Storage - payment API
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: payments.private.storage
    port: 443
  - name: Private Storage - storage001
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: storage001.private.storage
    port: 8898
  - name: Private Storage - storage002
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: storage002.private.storage
    port: 8898
  - name: Private Storage - storage003
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: storage003.private.storage
    port: 8898
  - name: Private Storage - storage004
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: storage004.private.storage
    port: 8898
  - name: Private Storage - storage005
    icon: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/private-storage-icon.svg
    check: "tcp-ping"
    url: storage005.private.storage
    port: 8898
  - name: Private Storage - matomo
    url: https://matomo.private.storage/

status-website:
  baseUrl: /end-users-upptime
  logoUrl: https://raw.githubusercontent.com/LeastAuthority/end-users-upptime/master/assets/upptime-icon.svg
  name: End Users
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by [GitHub](https://github.com/LeastAuthority/end-users-upptime)."
  introMessage: This site monitors the resources provided to end users of [Least Authority](https://leastauthority.com/) products and services.
  navbar:
    - title: End Users
      href: /end-users-upptime
    - title: Org Members
      href: /org-members-upptime
    - title: Infrastructure
      href: /infrastructure-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
